# Generated by Django 6.0.3 on 2026-04-04 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_promotionplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Description of admin action', max_length=255)),
                ('model_name', models.CharField(help_text='Model that was modified', max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('old_values', models.TextField(blank=True, help_text='Previous values (JSON)')),
                ('new_values', models.TextField(blank=True, help_text='New values (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_suspend', 'User Suspended'), ('user_ban', 'User Banned'), ('user_restore', 'User Restored'), ('product_deactivate', 'Product Deactivated'), ('product_reactivate', 'Product Reactivated'), ('seller_promote', 'Seller Promoted'), ('seller_demote', 'Seller Demoted'), ('report_resolved', 'Report Resolved'), ('review_removed', 'Review Removed'), ('listing_flagged', 'Listing Flagged'), ('other', 'Other')], max_length=50)),
                ('reason', models.TextField(help_text='Reason for this moderation action')),
                ('notes', models.TextField(blank=True, help_text='Additional admin notes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this action is currently in effect')),
                ('duration_days', models.IntegerField(blank=True, help_text='Duration in days (null = permanent)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this action expires (if temporary)', null=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='products.product')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_against', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonetizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_commission_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission % on each sale', max_digits=5)),
                ('seller_payout_threshold', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum amount before seller can withdraw', max_digits=10)),
                ('promotion_enabled', models.BooleanField(default=True, help_text='Enable/disable product promotions')),
                ('verification_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee to become verified seller', max_digits=10)),
                ('marketplace_tax_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax on platform transactions', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monetization_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Monetization Settings',
            },
        ),
        migrations.CreateModel(
            name='UserInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('product_view', 'Product View'), ('product_added_to_cart', 'Product Added to Cart'), ('product_rated', 'Product Rated'), ('seller_rated', 'Seller Rated'), ('product_reported', 'Product Reported'), ('seller_reported', 'Seller Reported'), ('review_posted', 'Review Posted'), ('seller_contacted', 'Seller Contacted'), ('purchase_completed', 'Purchase Completed'), ('refund_requested', 'Refund Requested'), ('dispute_opened', 'Dispute Opened')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_targeting', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Interaction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPromotionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('regular_user', 'Regular User'), ('verified_seller', 'Verified Seller'), ('premium_seller', 'Premium Seller'), ('suspended', 'Suspended'), ('banned', 'Permanently Banned')], default='regular_user', max_length=50)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_admin_verified', models.BooleanField(default=False)),
                ('reason_for_status', models.TextField(blank=True, help_text='Admin notes on why user has this status')),
                ('promoted_at', models.DateTimeField(auto_now=True)),
                ('promoted_by', models.ForeignKey(help_text='Admin who promoted/demoted this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
