# Generated by Django 5.2 on 2026-04-18 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_promotiontransaction_alter_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product_view', 'Product View'), ('contact_click', 'Contact Click')], db_index=True, max_length=30)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(blank=True, help_text='Where the interaction happened, e.g. detail page or homepage', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_engagements', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'event_type', 'created_at'], name='products_pr_product_96b2c5_idx'), models.Index(fields=['seller', 'event_type', 'created_at'], name='products_pr_seller__48feaa_idx')],
            },
        ),
    ]
