# Generated by Django 5.2 on 2026-04-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productengagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiontransaction',
            name='access_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='promotiontransaction',
            name='authorization_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='promotiontransaction',
            name='channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='promotiontransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotiontransaction',
            name='provider',
            field=models.CharField(default='paystack', max_length=30),
        ),
        migrations.AlterField(
            model_name='promotiontransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
